#!/usr/bin/env node

/**
 * updateMerkleRoot.js
 *
 * Updates the merkle root on-chain.
 * Now requires a depositTxHash to prevent duplicate processing.
 *
 * Usage: node updateMerkleRoot.js [depositTxHash]
 * Requires: merkle-data.json (generated by generateMerkle.js)
 */

import { ethers } from 'ethers';
import fs from 'fs';
import dotenv from 'dotenv';

dotenv.config();

const RPC_URL = process.env.RPC_URL || 'https://bsc-dataseed.binance.org/';
const PRIVATE_KEY = process.env.PRIVATE_KEY;
const BUYBACK_CONTRACT_ADDRESS = process.env.BUYBACK_CONTRACT_ADDRESS;

const DISTRIBUTOR_ABI = [
    'function updateMerkleRoot(bytes32 newMerkleRoot, bytes32 depositTxHash) external',
    'function currentEpoch() external view returns (uint256)',
    'function merkleRoot() external view returns (bytes32)',
    'function paused() external view returns (bool)',
    'function processedDeposits(bytes32) external view returns (bool)'
];

async function updateMerkleRoot(depositTxHash) {
    console.log('Updating Merkle Root on-chain...');

    // Validate environment variables
    if (!PRIVATE_KEY) {
        throw new Error('PRIVATE_KEY not set in .env');
    }
    if (!BUYBACK_CONTRACT_ADDRESS) {
        throw new Error('BUYBACK_CONTRACT_ADDRESS not set in .env');
    }

    // Load Merkle data
    if (!fs.existsSync('merkle-data.json')) {
        throw new Error('merkle-data.json not found. Run generateMerkle.js first.');
    }

    const merkleData = JSON.parse(fs.readFileSync('merkle-data.json', 'utf-8'));
    const merkleRoot = merkleData.root;

    console.log(`Merkle Root: ${merkleRoot}`);
    console.log(`Total Holders: ${merkleData.totalHolders}`);
    console.log(`Tokens Distributed: ${ethers.formatEther(merkleData.tokensDistributed)}`);
    console.log(`Deposit TxHash: ${depositTxHash}`);

    // Connect to blockchain
    const provider = new ethers.JsonRpcProvider(RPC_URL);
    const wallet = new ethers.Wallet(PRIVATE_KEY, provider);
    const contract = new ethers.Contract(BUYBACK_CONTRACT_ADDRESS, DISTRIBUTOR_ABI, wallet);

    console.log(`Operator Address: ${wallet.address}`);

    try {
        // Check contract state
        const isPaused = await contract.paused();
        if (isPaused) {
            throw new Error('Contract is paused');
        }

        // Check if deposit already processed
        const alreadyProcessed = await contract.processedDeposits(depositTxHash);
        if (alreadyProcessed) {
            console.log('Deposit already processed, skipping.');
            return null;
        }

        const currentEpoch = await contract.currentEpoch();
        const currentMerkleRoot = await contract.merkleRoot();

        console.log(`\nCurrent Epoch: ${currentEpoch}`);
        console.log(`Current Merkle Root: ${currentMerkleRoot}`);

        // Estimate gas
        console.log('\nEstimating gas...');
        const gasEstimate = await contract.updateMerkleRoot.estimateGas(merkleRoot, depositTxHash);
        console.log(`Estimated gas: ${gasEstimate.toString()}`);

        // Get current gas price
        const feeData = await provider.getFeeData();
        const gasPrice = feeData.gasPrice;
        console.log(`Gas price: ${ethers.formatUnits(gasPrice, 'gwei')} gwei`);

        const estimatedCost = gasEstimate * gasPrice;
        console.log(`Estimated cost: ${ethers.formatEther(estimatedCost)} BNB`);

        // Execute update
        console.log('\nSending transaction...');
        const tx = await contract.updateMerkleRoot(merkleRoot, depositTxHash, {
            gasLimit: gasEstimate * 120n / 100n // Add 20% buffer
        });

        console.log(`Transaction hash: ${tx.hash}`);
        console.log('Waiting for confirmation...');

        const receipt = await tx.wait();

        console.log(`\nMerkle root updated successfully!`);
        console.log(`Block: ${receipt.blockNumber}`);
        console.log(`Gas used: ${receipt.gasUsed.toString()}`);
        console.log(`New Epoch: ${Number(currentEpoch) + 1}`);

        // Parse events
        const merkleEvent = receipt.logs.find(log => {
            try {
                const parsed = contract.interface.parseLog(log);
                return parsed.name === 'MerkleRootUpdated';
            } catch {
                return false;
            }
        });

        if (merkleEvent) {
            const parsed = contract.interface.parseLog(merkleEvent);
            console.log('\nUpdate Details:');
            console.log(`  Epoch: ${parsed.args.epoch}`);
            console.log(`  Merkle Root: ${parsed.args.merkleRoot}`);
            console.log(`  Deposit TxHash: ${parsed.args.depositTxHash}`);
            console.log(`  Timestamp: ${new Date(Number(parsed.args.timestamp) * 1000).toISOString()}`);
        }

        // Update merkle-data.json with transaction info
        merkleData.transaction = {
            hash: tx.hash,
            blockNumber: receipt.blockNumber,
            gasUsed: receipt.gasUsed.toString(),
            timestamp: new Date().toISOString(),
            epoch: Number(currentEpoch) + 1,
            depositTxHash
        };

        fs.writeFileSync('merkle-data.json', JSON.stringify(merkleData, null, 2));

        // Archive this distribution
        const archiveDir = 'archives';
        if (!fs.existsSync(archiveDir)) {
            fs.mkdirSync(archiveDir);
        }

        const archiveFile = `${archiveDir}/epoch-${Number(currentEpoch) + 1}-${Date.now()}.json`;
        fs.writeFileSync(archiveFile, JSON.stringify(merkleData, null, 2));
        console.log(`\nArchived to ${archiveFile}`);

        return receipt;

    } catch (error) {
        console.error('\nError updating merkle root:', error.message);
        if (error.data) {
            console.error('Error data:', error.data);
        }
        throw error;
    }
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
    const depositTxHash = process.argv[2];
    if (!depositTxHash) {
        console.error('Usage: node updateMerkleRoot.js <depositTxHash>');
        process.exit(1);
    }
    updateMerkleRoot(depositTxHash).catch(console.error);
}

export { updateMerkleRoot };
